#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-wagon
Version  : 3.2.0
Release  : 1
URL      : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http/3.2.0/wagon-http-3.2.0.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http/3.2.0/wagon-http-3.2.0.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-file/3.2.0/wagon-file-3.2.0.jar
Source2  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-file/3.2.0/wagon-file-3.2.0.pom
Source3  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7/wagon-http-shared-1.0-beta-7.jar
Source4  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7/wagon-http-shared-1.0-beta-7.pom
Source5  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http-shared/2.7/wagon-http-shared-2.7.jar
Source6  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http-shared/2.7/wagon-http-shared-2.7.pom
Source7  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http/3.2.0/wagon-http-3.2.0-shaded.jar
Source8  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-http/3.2.0/wagon-http-3.2.0.pom
Source9  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2/wagon-provider-api-1.0-beta-2.jar
Source10  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2/wagon-provider-api-1.0-beta-2.pom
Source11  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.pom
Source12  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7/wagon-provider-api-1.0-beta-7.jar
Source13  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7/wagon-provider-api-1.0-beta-7.pom
Source14  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0/wagon-provider-api-1.0.jar
Source15  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0/wagon-provider-api-1.0.pom
Source16  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.0/wagon-provider-api-2.0.jar
Source17  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.0/wagon-provider-api-2.0.pom
Source18  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.10/wagon-provider-api-2.10.jar
Source19  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.10/wagon-provider-api-2.10.pom
Source20  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.7/wagon-provider-api-2.7.jar
Source21  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.7/wagon-provider-api-2.7.pom
Source22  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/3.2.0/wagon-provider-api-3.2.0.jar
Source23  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/3.2.0/wagon-provider-api-3.2.0.pom
Source24  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-providers/1.0-beta-7/wagon-providers-1.0-beta-7.pom
Source25  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-providers/2.0/wagon-providers-2.0.pom
Source26  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-providers/2.7/wagon-providers-2.7.pom
Source27  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-providers/3.2.0/wagon-providers-3.2.0.pom
Source28  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-ssh-common/2.0/wagon-ssh-common-2.0.jar
Source29  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-ssh-common/2.0/wagon-ssh-common-2.0.pom
Source30  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-ssh/2.0/wagon-ssh-2.0.jar
Source31  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-ssh/2.0/wagon-ssh-2.0.pom
Source32  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-webdav-jackrabbit/1.0-beta-7/wagon-webdav-jackrabbit-1.0-beta-7.jar
Source33  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-webdav-jackrabbit/1.0-beta-7/wagon-webdav-jackrabbit-1.0-beta-7.pom
Source34  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.7/wagon-webdav-jackrabbit-2.7.jar
Source35  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.7/wagon-webdav-jackrabbit-2.7.pom
Source36  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon/1.0-beta-2/wagon-1.0-beta-2.pom
Source37  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon/1.0-beta-6/wagon-1.0-beta-6.pom
Source38  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon/1.0-beta-7/wagon-1.0-beta-7.pom
Source39  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon/1.0/wagon-1.0.pom
Source40  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon/2.0/wagon-2.0.pom
Source41  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon/2.10/wagon-2.10.pom
Source42  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon/2.7/wagon-2.7.pom
Source43  : https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon/3.2.0/wagon-3.2.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-wagon-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-wagon package.
Group: Data

%description data
data components for the mvn-wagon package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-6
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/3.2.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/3.2.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.7
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.7
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.10
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.10
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.0
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh-common/2.0
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh-common/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh-common/2.0
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh-common/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-file/3.2.0
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-file/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-file/3.2.0
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-file/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/3.2.0
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/1.0-beta-7
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/1.0-beta-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/2.7
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/2.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/2.0
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-6
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/3.2.0
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-7
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.7
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.10
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-2
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.0
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/1.0-beta-7
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/1.0-beta-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/1.0-beta-7
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/1.0-beta-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.7
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.7
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/2.7
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/2.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/2.7
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/2.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh/2.0
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh/2.0
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh/2.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-file/3.2.0/wagon-provider-api-2.7.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-file/3.2.0/wagon-provider-api-2.7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7/wagon-1.0-beta-7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7/wagon-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/2.7/wagon-2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http-shared/2.7/wagon-2.10.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0/wagon-file-3.2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0/wagon-file-3.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-http/3.2.0/wagon-http-3.2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2/wagon-provider-api-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2/wagon-provider-api-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-http-shared-2.7.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7/wagon-http-3.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7/wagon-provider-api-1.0-beta-2.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0/wagon-http-shared-1.0-beta-7.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0/wagon-http-shared-1.0-beta-7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.0/wagon-provider-api-2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.0/wagon-provider-api-2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.10/wagon-provider-api-1.0-beta-7.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.10/wagon-provider-api-1.0-beta-7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.7/wagon-provider-api-1.0-beta-2.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.7/wagon-provider-api-1.0-beta-6.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/3.2.0/wagon-http-3.2.0-shaded.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-provider-api/3.2.0/wagon-http-shared-2.7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/1.0-beta-7/wagon-provider-api-3.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/2.0/wagon-providers-2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/2.7/wagon-providers-1.0-beta-7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-providers/3.2.0/wagon-provider-api-3.2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh-common/2.0/wagon-provider-api-2.10.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh-common/2.0/wagon-provider-api-2.10.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh/2.0/wagon-2.7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-ssh/2.0/wagon-3.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/1.0-beta-7/wagon-webdav-jackrabbit-2.7.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/1.0-beta-7/wagon-webdav-jackrabbit-2.7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.7/wagon-1.0-beta-2.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.7/wagon-1.0-beta-6.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-2/wagon-webdav-jackrabbit-1.0-beta-7.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-6/wagon-providers-3.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0-beta-7/wagon-ssh-common-2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/1.0/wagon-providers-2.7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.0/wagon-webdav-jackrabbit-1.0-beta-7.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.10/wagon-ssh-2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/2.7/wagon-ssh-2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/wagon/wagon/3.2.0/wagon-ssh-common-2.0.jar
